app:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
      - 3000:3000
  links:
    - postgres
  volumes:
    - .:/usr/src/app
  environment:
    RAILS_ENV: development
    POSTGRES_USER: 'clutter'
    POSTGRES_PASSWORD: 'somepassword'

postgres:
  image: postgres:10.1
  environment:
    POSTGRES_USER: 'clutter'
    POSTGRES_PASSWORD: 'somepassword'
    POSTGRES_PORT: 5432
